import { AxiosResponse } from 'axios';
import { solvestackAPIClient } from './clients';
import MeetupEvent from 'types/meetupEvents';

const events = [
    {
        created: 1596754313000,
        duration: 10800000,
        id: 'cctdwrybclblb',
        name: 'Solvestack Mentorship: Wire up your backend to your frontend website',
        date_in_series_pattern: false,
        status: 'past',
        time: 1596916800000,
        local_date: '2020-08-08',
        local_time: '13:00',
        updated: 1596930465000,
        utc_offset: -25200000,
        waitlist_count: 0,
        yes_rsvp_count: 9,
        venue: {
            id: 26964551,
            name: 'Peerlogic',
            lat: 33.502689361572266,
            lon: -111.93209075927734,
            repinned: true,
            address_1: '6900 E Camelback Rd Ste. 805',
            city: 'Scottsdale',
            country: 'us',
            localized_country_name: 'USA',
            zip: '85251',
            state: 'AZ',
        },
        is_online_event: false,
        group: {
            created: 1596751657000,
            name: 'Solvestack: The Software Engineering Mentorship Program',
            id: 34061797,
            join_mode: 'open',
            lat: 33.52000045776367,
            lon: -111.91000366210938,
            urlname: 'Solvestack-The-Software-Engineering-Mentorship-Program',
            who: 'Mentees',
            localized_location: 'Scottsdale, AZ',
            state: 'AZ',
            country: 'us',
            region: 'en_US',
            timezone: 'US/Arizona',
        },
        link: 'https://www.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events/cctdwrybclblb/',
        description:
            '<p>This both an online and in person event. We have 4 mentees so far showing in person! Make sure to bring a mask. We have hand sanitizer and order pizza.</p> <p><a href="https://zoom.us/j/2078655596" class="linkified">https://zoom.us/j/2078655596</a></p> <p>1pm - Welcome, get to know each other, special guest Caylee Harrington speaking<br/>1:30pm - Review glossary and key concepts from last time, with candy<br/>2pm - Lesson: wiring backend to a website<br/>3pm - Students who are finished up can help out any struggling students (don\'t leave - let\'s figure it out together!)<br/>4pm Goodbyes</p> ',
        how_to_find_us:
            'Park in front of Amtrust Bank and enter through the double doors titled "CAMELBACK TOWER" and Ana will meet you. Text her at 480-652-5408.',
        visibility: 'public',
        member_pay_fee: false,
        featured_photo: {
            id: 491687998,
            highres_link: 'https://secure.meetupstatic.com/photos/event/b/b/7/e/highres_491687998.jpeg',
            photo_link: 'https://secure.meetupstatic.com/photos/event/b/b/7/e/600_491687998.jpeg',
            thumb_link: 'https://secure.meetupstatic.com/photos/event/b/b/7/e/thumb_491687998.jpeg',
            type: 'event',
            base_url: 'https://secure.meetupstatic.com',
        },
    },
    {
        created: 1596948517000,
        duration: 14400000,
        id: '272458665',
        name: 'Solvestack Mentorship: Performing a Search from Frontend to Backend',
        date_in_series_pattern: false,
        status: 'past',
        time: 1597521600000,
        local_date: '2020-08-15',
        local_time: '13:00',
        updated: 1597538809000,
        utc_offset: -25200000,
        waitlist_count: 0,
        yes_rsvp_count: 10,
        venue: {
            id: 26964551,
            name: 'Peerlogic',
            lat: 33.502689361572266,
            lon: -111.93209075927734,
            repinned: true,
            address_1: '6900 E Camelback Rd Ste. 805',
            city: 'Scottsdale',
            country: 'us',
            localized_country_name: 'USA',
            zip: '85251',
            state: 'AZ',
        },
        is_online_event: false,
        group: {
            created: 1596751657000,
            name: 'Solvestack: The Software Engineering Mentorship Program',
            id: 34061797,
            join_mode: 'open',
            lat: 33.52000045776367,
            lon: -111.91000366210938,
            urlname: 'Solvestack-The-Software-Engineering-Mentorship-Program',
            who: 'Mentees',
            localized_location: 'Scottsdale, AZ',
            state: 'AZ',
            country: 'us',
            region: 'en_US',
            timezone: 'US/Arizona',
        },
        link: 'https://www.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events/272458665/',
        description:
            '<p>This both an online and in person event. We have 4 mentees so far showing in person! Make sure to bring a mask. We have hand sanitizer and order pizza.</p> <p><a href="https://zoom.us/j/2078655596" class="linkified">https://zoom.us/j/2078655596</a></p> <p>Prerequisites:<br/>Sign up for a Github account if you don\'t have one, and then install Python3 <a href="https://www.python.org/downloads/" class="linkified">https://www.python.org/downloads/</a>, Node/NPM <a href="https://nodejs.org/en/download/" class="linkified">https://nodejs.org/en/download/</a>, DBeaver <a href="https://dbeaver.io/download/" class="linkified">https://dbeaver.io/download/</a> and Postman <a href="https://www.postman.com/downloads/" class="linkified">https://www.postman.com/downloads/</a>.</p> <p>1pm - Welcome, get to know each other<br/>1:15pm - Review glossary and key concepts from last time, with candy<br/>2:45pm - Run the backend and run the frontend<br/>2pm - Lesson: UI search component<br/>2:30 - Lesson: Backend filters<br/>3pm- Lesson: Debugging<br/>4pm Goodbyes</p> <p>Frontend languages and libraries we\'ll be using: React and Typescript<br/>Backend languages and libraries we\'ll be using: Python and Django REST Framework</p> ',
        how_to_find_us:
            'Park in front of Amtrust Bank (don\'t worry you won\'t be towed!). Then, enter through the double doors titled "CAMELBACK TOWER" and Ana will meet you. Text her at 480-652-5408.',
        visibility: 'public',
        member_pay_fee: false,
        featured_photo: {
            id: 491749253,
            highres_link: 'https://secure.meetupstatic.com/photos/event/c/0/6/5/highres_491749253.jpeg',
            photo_link: 'https://secure.meetupstatic.com/photos/event/c/0/6/5/600_491749253.jpeg',
            thumb_link: 'https://secure.meetupstatic.com/photos/event/c/0/6/5/thumb_491749253.jpeg',
            type: 'event',
            base_url: 'https://secure.meetupstatic.com',
        },
    },
    {
        created: 1597541037000,
        duration: 14400000,
        id: '272604345',
        name: 'Solvestack Mentorship: Backend - Python data analysis',
        date_in_series_pattern: false,
        status: 'past',
        time: 1598731200000,
        local_date: '2020-08-29',
        local_time: '13:00',
        updated: 1598748540000,
        utc_offset: -25200000,
        waitlist_count: 0,
        yes_rsvp_count: 14,
        is_online_event: false,
        group: {
            created: 1596751657000,
            name: 'Solvestack: The Software Engineering Mentorship Program',
            id: 34061797,
            join_mode: 'open',
            lat: 33.52000045776367,
            lon: -111.91000366210938,
            urlname: 'Solvestack-The-Software-Engineering-Mentorship-Program',
            who: 'Mentees',
            localized_location: 'Scottsdale, AZ',
            state: 'AZ',
            country: 'us',
            region: 'en_US',
            timezone: 'US/Arizona',
        },
        link: 'https://www.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events/272604345/',
        description:
            '<p>This both an online and in person event. We have 6 mentees so far showing in person! Make sure to bring a mask. We have hand sanitizer and order pizza.</p> <p><a href="https://zoom.us/j/2078655596" class="linkified">https://zoom.us/j/2078655596</a></p> <p>Prerequisites:<br/>Sign up for a Github account if you don\'t have one, and then install Python3 <a href="https://installpython3.com/" class="linkified">https://installpython3.com/</a>, Node/NPM <a href="https://nodejs.org/en/download/" class="linkified">https://nodejs.org/en/download/</a>, DBeaver <a href="https://dbeaver.io/download/" class="linkified">https://dbeaver.io/download/</a> and Postman <a href="https://www.postman.com/downloads/" class="linkified">https://www.postman.com/downloads/</a>.</p> <p>1pm - Welcome, get to know each other<br/>1:15pm - Review glossary and key concepts from last time, with candy<br/>2pm - Select a data source<br/>2:30pm - Lesson: Play with the data<br/>3pm- Lesson: Access relevant metrics from Django REST Framework<br/>4:30pm- Goodbyes</p> <p>Backend languages and libraries we\'ll be using: Python, numpy or pandas, and Django REST Framework</p> ',
        visibility: 'public',
        member_pay_fee: false,
        featured_photo: {
            id: 491915982,
            highres_link: 'https://secure.meetupstatic.com/photos/event/8/c/8/e/highres_491915982.jpeg',
            photo_link: 'https://secure.meetupstatic.com/photos/event/8/c/8/e/600_491915982.jpeg',
            thumb_link: 'https://secure.meetupstatic.com/photos/event/8/c/8/e/thumb_491915982.jpeg',
            type: 'event',
            base_url: 'https://secure.meetupstatic.com',
        },
    },
    {
        created: 1599177981000,
        duration: 7200000,
        id: '273018741',
        name: 'Hook into an API',
        date_in_series_pattern: false,
        status: 'past',
        time: 1599253200000,
        local_date: '2020-09-04',
        local_time: '14:00',
        updated: 1599262188000,
        utc_offset: -25200000,
        waitlist_count: 0,
        yes_rsvp_count: 7,
        venue: {
            id: 26906060,
            name: 'Online event',
            repinned: false,
            country: '',
            localized_country_name: '',
        },
        is_online_event: true,
        group: {
            created: 1596751657000,
            name: 'Solvestack: The Software Engineering Mentorship Program',
            id: 34061797,
            join_mode: 'open',
            lat: 33.52000045776367,
            lon: -111.91000366210938,
            urlname: 'Solvestack-The-Software-Engineering-Mentorship-Program',
            who: 'Mentees',
            localized_location: 'Scottsdale, AZ',
            state: 'AZ',
            country: 'us',
            region: 'en_US',
            timezone: 'US/Arizona',
        },
        link: 'https://www.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events/273018741/',
        description:
            '<p>We are going make request calls to an API (probably a weather API). We\'ll use the documentation to learn how to retrieve info. From there we will build an app to display the info.</p> <p>Prerequisites:<br/>please make sure the following are installed:</p> <p>Node &gt;= 8.10<br/><a href="https://nodejs.org/en/download/" class="linkified">https://nodejs.org/en/download/</a><br/>check node version by typing node -v in command line</p> <p>npm &gt;= 5.6<br/>ships with node, if your version is outdated, look up how to update<br/>check npm version by typing npm -v in command line</p> ',
        how_to_find_us: 'https://asu.zoom.us/my/chrissyalbert',
        visibility: 'public',
        member_pay_fee: false,
        featured_photo: {
            id: 492151418,
            highres_link: 'https://secure.meetupstatic.com/photos/event/7/a/b/a/highres_492151418.jpeg',
            photo_link: 'https://secure.meetupstatic.com/photos/event/7/a/b/a/600_492151418.jpeg',
            thumb_link: 'https://secure.meetupstatic.com/photos/event/7/a/b/a/thumb_492151418.jpeg',
            type: 'event',
            base_url: 'https://secure.meetupstatic.com',
        },
    },
    {
        created: 1599170532000,
        duration: 7200000,
        id: '273016506',
        name: 'Software Installation Help',
        date_in_series_pattern: false,
        status: 'past',
        time: 1599262200000,
        local_date: '2020-09-04',
        local_time: '16:30',
        updated: 1599272292000,
        utc_offset: -25200000,
        waitlist_count: 0,
        yes_rsvp_count: 5,
        venue: {
            id: 26906060,
            name: 'Online event',
            repinned: false,
            country: '',
            localized_country_name: '',
        },
        is_online_event: true,
        group: {
            created: 1596751657000,
            name: 'Solvestack: The Software Engineering Mentorship Program',
            id: 34061797,
            join_mode: 'open',
            lat: 33.52000045776367,
            lon: -111.91000366210938,
            urlname: 'Solvestack-The-Software-Engineering-Mentorship-Program',
            who: 'Mentees',
            localized_location: 'Scottsdale, AZ',
            state: 'AZ',
            country: 'us',
            region: 'en_US',
            timezone: 'US/Arizona',
        },
        link: 'https://www.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events/273016506/',
        description:
            "<p>You'll need some softwares installed to follow along at the meetings. Want to start geting started but aren't sure what you need? Think you know what you need but are running into problems getting it running? Want to hang out with consummate professionals but can't stop bristling when you're confronted with the word \"softwares?\" The last one might be tough, but we're here to help!</p> <p>All you need is a computer and the ability to download and install software on it. Anything from the past decade should work, but it's all been confirmed on OSX, Windows 7 &amp; 10, and Ubuntu 18.04. Besides, it's the most fun you'll have on a Friday evening in a coronavirus hotspot!</p> <p>- This event is virtual and strictly BYOB<br/>- Long sighs and profane outbursts will be sympathized. If nothing else, it's been a loooooong[masked] months (already?!)<br/>- Everyone is welcome, but regardless of any personal traditions, Rebecca Black song(s) must remain at a respectful (entirely inaudible) volume</p> ",
        how_to_find_us: 'https://us02web.zoom.us/s/5888995679',
        visibility: 'public',
        member_pay_fee: false,
        featured_photo: {
            id: 492150260,
            highres_link: 'https://secure.meetupstatic.com/photos/event/7/6/3/4/highres_492150260.jpeg',
            photo_link: 'https://secure.meetupstatic.com/photos/event/7/6/3/4/600_492150260.jpeg',
            thumb_link: 'https://secure.meetupstatic.com/photos/event/7/6/3/4/thumb_492150260.jpeg',
            type: 'event',
            base_url: 'https://secure.meetupstatic.com',
        },
    },
    {
        created: 1598420822000,
        duration: 14400000,
        id: '272817022',
        name: 'Solvestack Mentorship: Backend in Node.js, MongoDB and Mongoose',
        date_in_series_pattern: false,
        status: 'past',
        time: 1599336000000,
        local_date: '2020-09-05',
        local_time: '13:00',
        updated: 1599353673000,
        utc_offset: -25200000,
        waitlist_count: 0,
        yes_rsvp_count: 13,
        venue: {
            id: 26964551,
            name: 'Peerlogic',
            lat: 33.502689361572266,
            lon: -111.93209075927734,
            repinned: true,
            address_1: '6900 E Camelback Rd Ste. 805',
            city: 'Scottsdale',
            country: 'us',
            localized_country_name: 'USA',
            zip: '85251',
            state: 'AZ',
        },
        is_online_event: false,
        group: {
            created: 1596751657000,
            name: 'Solvestack: The Software Engineering Mentorship Program',
            id: 34061797,
            join_mode: 'open',
            lat: 33.52000045776367,
            lon: -111.91000366210938,
            urlname: 'Solvestack-The-Software-Engineering-Mentorship-Program',
            who: 'Mentees',
            localized_location: 'Scottsdale, AZ',
            state: 'AZ',
            country: 'us',
            region: 'en_US',
            timezone: 'US/Arizona',
        },
        link: 'https://www.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events/272817022/',
        description:
            '<p>This both an online and in person event. We have 6 mentees so far showing in person! Make sure to bring a mask. We have hand sanitizer and order pizza.</p> <p><a href="https://zoom.us/j/2078655596" class="linkified">https://zoom.us/j/2078655596</a></p> <p>Prerequisites:<br/>Sign up for a Github account if you don\'t have one, and then install Python3 <a href="https://www.python.org/downloads/" class="linkified">https://www.python.org/downloads/</a> , Node/NPM <a href="https://nodejs.org/en/download/" class="linkified">https://nodejs.org/en/download/</a> , DBeaver <a href="https://dbeaver.io/download/" class="linkified">https://dbeaver.io/download/</a> and Postman <a href="https://www.postman.com/downloads/" class="linkified">https://www.postman.com/downloads/</a> .</p> <p>1pm - Welcome, get to know each other<br/>1:15pm - Review glossary and key concepts from last time, with candy<br/>2pm - Lesson: Create our Mongo database<br/>2:30pm - Lesson: Create our JS backend<br/>4:30pm- Goodbyes</p> <p>Backend languages and libraries we\'ll be using: Node.js, Mongoose</p> ',
        how_to_find_us:
            'Park in front of Amtrust Bank and enter through the double doors titled "CAMELBACK TOWER" and Ana will meet you. Text her at 480-652-5408.',
        visibility: 'public',
        member_pay_fee: false,
        featured_photo: {
            id: 492011538,
            highres_link: 'https://secure.meetupstatic.com/photos/event/2/d/1/2/highres_492011538.jpeg',
            photo_link: 'https://secure.meetupstatic.com/photos/event/2/d/1/2/600_492011538.jpeg',
            thumb_link: 'https://secure.meetupstatic.com/photos/event/2/d/1/2/thumb_492011538.jpeg',
            type: 'event',
            base_url: 'https://secure.meetupstatic.com',
        },
    },
    {
        created: 1598816526000,
        duration: 14400000,
        id: '272918391',
        name: 'Solvestack Mentorship: Backend - Python and Django ORM',
        date_in_series_pattern: false,
        status: 'past',
        time: 1599940800000,
        local_date: '2020-09-12',
        local_time: '13:00',
        updated: 1599957050000,
        utc_offset: -25200000,
        waitlist_count: 0,
        yes_rsvp_count: 11,
        is_online_event: true,
        group: {
            created: 1596751657000,
            name: 'Solvestack: The Software Engineering Mentorship Program',
            id: 34061797,
            join_mode: 'open',
            lat: 33.52000045776367,
            lon: -111.91000366210938,
            urlname: 'Solvestack-The-Software-Engineering-Mentorship-Program',
            who: 'Mentees',
            localized_location: 'Scottsdale, AZ',
            state: 'AZ',
            country: 'us',
            region: 'en_US',
            timezone: 'US/Arizona',
        },
        link: 'https://www.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events/272918391/',
        description:
            '<p>This both an online and in person event. Make sure to bring a mask. We have hand sanitizer and order pizza.</p> <p><a href="https://zoom.us/j/2078655596" class="linkified">https://zoom.us/j/2078655596</a></p> <p>Prerequisites:<br/>Sign up for a Github account if you don\'t have one, and then install Python3 <a href="https://installpython3.com/" class="linkified">https://installpython3.com/</a>, Node/NPM <a href="https://nodejs.org/en/download/" class="linkified">https://nodejs.org/en/download/</a>, DBeaver <a href="https://dbeaver.io/download/" class="linkified">https://dbeaver.io/download/</a> and Postman <a href="https://www.postman.com/downloads/" class="linkified">https://www.postman.com/downloads/</a>.</p> <p>1pm - Welcome, get to know each other<br/>1:15pm - Review glossary and key concepts from last time, with candy<br/>2pm - Select a data source<br/>2:30pm - Lesson: Play with the data<br/>3pm- Lesson: Access relevant metrics from Django REST Framework<br/>4:30pm- Goodbyes</p> <p>Backend languages and libraries we\'ll be using: Python, Django</p> ',
        visibility: 'public',
        member_pay_fee: false,
        featured_photo: {
            id: 492099315,
            highres_link: 'https://secure.meetupstatic.com/photos/event/9/9/9/3/highres_492099315.jpeg',
            photo_link: 'https://secure.meetupstatic.com/photos/event/9/9/9/3/600_492099315.jpeg',
            thumb_link: 'https://secure.meetupstatic.com/photos/event/9/9/9/3/thumb_492099315.jpeg',
            type: 'event',
            base_url: 'https://secure.meetupstatic.com',
        },
    },
    {
        created: 1599594850000,
        duration: 7200000,
        id: '273120532',
        name: 'Hook into an API, part 2',
        date_in_series_pattern: false,
        status: 'past',
        time: 1600110000000,
        local_date: '2020-09-14',
        local_time: '12:00',
        updated: 1600119984000,
        utc_offset: -25200000,
        waitlist_count: 0,
        yes_rsvp_count: 5,
        venue: {
            id: 26906060,
            name: 'Online event',
            repinned: false,
            country: '',
            localized_country_name: '',
        },
        is_online_event: true,
        group: {
            created: 1596751657000,
            name: 'Solvestack: The Software Engineering Mentorship Program',
            id: 34061797,
            join_mode: 'open',
            lat: 33.52000045776367,
            lon: -111.91000366210938,
            urlname: 'Solvestack-The-Software-Engineering-Mentorship-Program',
            who: 'Mentees',
            localized_location: 'Scottsdale, AZ',
            state: 'AZ',
            country: 'us',
            region: 'en_US',
            timezone: 'US/Arizona',
        },
        link: 'https://www.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events/273120532/',
        description:
            '<p>For this session we will be continuing where we left off.<br/>1. We will add logic (writing functions) so that our user input will modify our API call and return data for the city the user requested.<br/>2. We will create display components for the web page so that the user can see city weather data in an easy to understand format.<br/>3. We will modify our component files to keep the React components pure--"do only one thing."<br/>4. I will show a diagram of how data flows down in React so that we can make sure our state is always at the top of the hierarchy.</p> <p>Prerequisites:<br/>please make sure the following are installed:</p> <p>Node &gt;= 8.10<br/><a href="https://nodejs.org/en/download/" class="linkified">https://nodejs.org/en/download/</a><br/>check node version by typing node -v in command line</p> <p>npm &gt;= 5.6<br/>ships with node, if your version is outdated, look up how to update<br/>check npm version by typing npm -v in command line</p> <p>If you haven\'t attended the first workshop, please let me know in the comments below so I can help catch you up.</p> ',
        how_to_find_us: 'https://asu.zoom.us/my/chrissyalbert',
        visibility: 'public',
        member_pay_fee: false,
        featured_photo: {
            id: 492151418,
            highres_link: 'https://secure.meetupstatic.com/photos/event/7/a/b/a/highres_492151418.jpeg',
            photo_link: 'https://secure.meetupstatic.com/photos/event/7/a/b/a/600_492151418.jpeg',
            thumb_link: 'https://secure.meetupstatic.com/photos/event/7/a/b/a/thumb_492151418.jpeg',
            type: 'event',
            base_url: 'https://secure.meetupstatic.com',
        },
    },
    {
        created: 1600193117000,
        duration: 7200000,
        id: '273276731',
        name: 'Hook into an API, part 2',
        date_in_series_pattern: false,
        status: 'past',
        time: 1600455600000,
        local_date: '2020-09-18',
        local_time: '12:00',
        updated: 1600465682000,
        utc_offset: -25200000,
        waitlist_count: 0,
        yes_rsvp_count: 6,
        venue: {
            id: 26906060,
            name: 'Online event',
            repinned: false,
            country: '',
            localized_country_name: '',
        },
        is_online_event: true,
        group: {
            created: 1596751657000,
            name: 'Solvestack: The Software Engineering Mentorship Program',
            id: 34061797,
            join_mode: 'open',
            lat: 33.52000045776367,
            lon: -111.91000366210938,
            urlname: 'Solvestack-The-Software-Engineering-Mentorship-Program',
            who: 'Mentees',
            localized_location: 'Scottsdale, AZ',
            state: 'AZ',
            country: 'us',
            region: 'en_US',
            timezone: 'US/Arizona',
        },
        link: 'https://www.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events/273276731/',
        description:
            '<p>Please note that this is a rescheduled event.</p> <p>For this session we will be continuing where we left off from our previous Hook into an API meetup.</p> <p>1. We will add logic (writing functions) so that our user input will modify our API call and return data for the city the user requested.<br/>2. We will create display components for the web page so that the user can see city weather data in an easy to understand format.<br/>3. We will modify our component files to keep the React components pure--"do only one thing."<br/>4. I will show a diagram of how data flows down in React so that we can make sure our state is always at the top of the hierarchy.</p> <p>Prerequisites:<br/>please make sure the following are installed:</p> <p>Node &gt;= 8.10<br/><a href="https://nodejs.org/en/download/" class="linkified">https://nodejs.org/en/download/</a><br/>check node version by typing node -v in command line</p> <p>npm &gt;= 5.6<br/>ships with node, if your version is outdated, look up how to update<br/>check npm version by typing npm -v in command line</p> <p>If you haven\'t attended the first workshop, please let me know in the comments below so I can help catch you up.</p> ',
        how_to_find_us: 'https://asu.zoom.us/my/chrissyalbert',
        visibility: 'public',
        member_pay_fee: false,
        featured_photo: {
            id: 492151418,
            highres_link: 'https://secure.meetupstatic.com/photos/event/7/a/b/a/highres_492151418.jpeg',
            photo_link: 'https://secure.meetupstatic.com/photos/event/7/a/b/a/600_492151418.jpeg',
            thumb_link: 'https://secure.meetupstatic.com/photos/event/7/a/b/a/thumb_492151418.jpeg',
            type: 'event',
            base_url: 'https://secure.meetupstatic.com',
        },
    },
    {
        created: 1599610685000,
        duration: 14400000,
        id: '273124872',
        name: 'Solvestack Mentorship: Hooking into the Meetup API from the Frontend',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1600545600000,
        local_date: '2020-09-19',
        local_time: '13:00',
        updated: 1599689738000,
        utc_offset: -25200000,
        waitlist_count: 0,
        yes_rsvp_count: 12,
        venue: {
            id: 26964551,
            name: 'Peerlogic',
            lat: 33.502689361572266,
            lon: -111.93209075927734,
            repinned: true,
            address_1: '6900 E Camelback Rd Ste. 805',
            city: 'Scottsdale',
            country: 'us',
            localized_country_name: 'USA',
            zip: '85251',
            state: 'AZ',
        },
        is_online_event: false,
        group: {
            created: 1596751657000,
            name: 'Solvestack: The Software Engineering Mentorship Program',
            id: 34061797,
            join_mode: 'open',
            lat: 33.52000045776367,
            lon: -111.91000366210938,
            urlname: 'Solvestack-The-Software-Engineering-Mentorship-Program',
            who: 'Mentees',
            localized_location: 'Scottsdale, AZ',
            state: 'AZ',
            country: 'us',
            region: 'en_US',
            timezone: 'US/Arizona',
        },
        link: 'https://www.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events/273124872/',
        description:
            '<p>This is gonna be so meta! A meetup about meetup API and using it to make cool React components. Yo dawg.</p> <p>This both an online and in person event. Make sure to bring a mask. We have hand sanitizer and order pizza.</p> <p><a href="https://zoom.us/j/2078655596" class="linkified">https://zoom.us/j/2078655596</a></p> <p>Prerequisites:<br/>Sign up for a Github account if you don\'t have one, and then install Python3 <a href="https://www.python.org/downloads/" class="linkified">https://www.python.org/downloads/</a> , Node/NPM <a href="https://nodejs.org/en/download/" class="linkified">https://nodejs.org/en/download/</a> , DBeaver <a href="https://dbeaver.io/download/" class="linkified">https://dbeaver.io/download/</a> and Postman <a href="https://www.postman.com/downloads/" class="linkified">https://www.postman.com/downloads/</a> .</p> <p>1pm - Welcome, get to know each other<br/>1:15pm - Review glossary and key concepts from last time, with candy<br/>2pm - Review potentially interesting REST API calls we can make<br/>2:30pm - Lesson: Create a component that shows the Featured Mentors<br/>4:30pm- Goodbyes</p> <p>Backend languages and libraries we\'ll be using: React.js and Typescript</p> ',
        how_to_find_us:
            'Park in front of Amtrust Bank and enter through the double doors titled "CAMELBACK TOWER" and Ana will meet you. Text her at 480-652-5408.',
        visibility: 'public',
        member_pay_fee: false,
        featured_photo: {
            id: 492244372,
            highres_link: 'https://secure.meetupstatic.com/photos/event/1/1/1/4/highres_492244372.jpeg',
            photo_link: 'https://secure.meetupstatic.com/photos/event/1/1/1/4/600_492244372.jpeg',
            thumb_link: 'https://secure.meetupstatic.com/photos/event/1/1/1/4/thumb_492244372.jpeg',
            type: 'event',
            base_url: 'https://secure.meetupstatic.com',
        },
    },
];

export default {
    eventsList(): Promise<AxiosResponse<MeetupEvent[]>> {
        return solvestackAPIClient.get<Array<MeetupEvent>>(
            'https://api.meetup.com/Solvestack-The-Software-Engineering-Mentorship-Program/events?page=20&status=upcoming',
        );
    },
    mockedMeetupEventsList: (): MeetupEvent[] => events,
};
